version: '3.3'
services:
  db:
    image: mysql
    restart: always
    cap_add:
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db
