version: '3.3'

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'local-db'
    ports:
      - '3306:3306'
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - my-db
    networks:
      - bridgeNet

  web:
    build: .
    ports: 
      - '8080:8080'
    networks:
      - bridgeNet
    depends_on:
      db:
        condition: service_healthy

networks:
  bridgeNet:
    driver: bridge
